import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#100A1F",
  },
  container: {
    flex: 1,
  },
  authContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  authContent: {
    flex: 1,
    justifyContent: "center",
  },
  
  // Header Section Styles
  authHeader: {
    marginBottom: 48,
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 32,
  },
  logoWrapper: {
    padding: 8,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 20,
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  authLogo: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  brandText: {
    fontSize: 28,
    fontFamily: "JetBrainsMono-Bold",
    color: "#FFF",
    letterSpacing: -0.5,
  },
  titleSection: {
    gap: 8,
  },
  authTitle: {
    fontSize: 32,
    fontFamily: "JetBrainsMono-Bold",
    color: "#FFF",
    lineHeight: 38,
    letterSpacing: -0.5,
  },
  authSubTitle: {
    fontSize: 16,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
    lineHeight: 22,
    marginTop: 4,
  },
  
  // Form Section Styles
  formSection: {
    gap: 24,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
    color: "#FFF",
    marginLeft: 4,
  },
  inputWrapper: {
    borderWidth: 1.5,
    borderColor: "rgba(170, 170, 170, 0.3)",
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  inputWrapperFocused: {
    borderColor: "#007AFF",
    backgroundColor: "rgba(0, 122, 255, 0.05)",
    shadowColor: "#007AFF",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  authInput: {
    padding: 16,
    fontSize: 16,
    color: "#FFF",
    fontFamily: "JetBrainsMono-Medium",
    minHeight: 56,
  },
  
  // Button Section Styles
  buttonSection: {
    paddingBottom: 32,
    gap: 24,
  },
  authButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 18,
    borderRadius: 16,
    shadowColor: "#007AFF",
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  authButtonText: {
    color: "#FFF",
    fontSize: 18,
    fontFamily: "JetBrainsMono-Bold",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  signInSection: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  signInText: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
  },
  signInLink: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Bold",
    color: "#007AFF",
  },
  
  // Existing styles (unchanged)
  sidebar: {
    width: 250,
    backgroundColor: "#201A2F",
    padding: 10,
    borderRightWidth: 1,
    borderRightColor: "#302A4F",
  },
  newChatButton: {
    backgroundColor: "#007AFF",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  newChatButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "JetBrainsMono-Bold",
  },
  chatItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#302A4F",
    flex: 1,
  },
  chatItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 10,
  },
  sidebarButtons: {
    marginTop: "auto",
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#302A4F",
  },
  sidebarButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  sidebarButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    marginLeft: 10,
    fontFamily: "JetBrainsMono-Medium",
  },
  chatItemText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "JetBrainsMono-Medium",
  },
  authText: {
    fontSize: 16,
    fontFamily: "JetBrainsMono-Medium",
    color: "#FFF"
  },
  chatContainer: {
    padding: 12,
  },
  messageContainer: {
    maxWidth: "75%",
    padding: 12,
    marginVertical: 6,
    borderRadius: 18,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  myMessage: {
    alignSelf: "flex-end",
    backgroundColor: "#DCF8C6",
    borderBottomRightRadius: 4,
  },
  otherMessage: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  messageText: {
    fontSize: 16,
    color: "#333",
    fontFamily: "JetBrainsMono-Medium",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: "#555555",
    backgroundColor: "#100A1F",
  },
  input: {
    flex: 1,
    height: 45,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: "#FAFAFA",
    fontFamily: "JetBrainsMono-Medium",
  },
  sendButton: {
    marginLeft: 10,
    backgroundColor: "#007AFF",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 25,
  },
  sendText: {
    color: "#FFF",
    fontSize: 16,
    fontFamily: "JetBrainsMono-Bold",
  },
  loadingContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  loadingText: {
    marginLeft: 10,
    fontSize: 14,
    color: "#AAA",
    fontFamily: "JetBrainsMono-Medium",
  },
  errorContainer: {
    padding: 10,
    backgroundColor: "#FFD2D2",
    alignItems: "center",
  },
  errorText: {
    color: "#D8000C",
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
  },
  
  // Website Generation Screen Styles
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#302A4F",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: "JetBrainsMono-Bold",
    color: "#FFF",
    textAlign: "center",
    marginRight: 32,
  },
  headerSpacer: {
    width: 32,
  },
  scrollContainer: {
    flex: 1,
    padding: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "JetBrainsMono-Bold",
    color: "#FFF",
    marginBottom: 12,
  },
  websiteTypeContainer: {
    marginBottom: 24,
  },
  websiteTypeChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#302A4F",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    marginRight: 10,
  },
  websiteTypeChipSelected: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  websiteTypeChipText: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
  },
  websiteTypeChipTextSelected: {
    color: "#FFF",
  },
  inputSection: {
    marginBottom: 24,
  },
  textArea: {
    borderWidth: 1,
    borderColor: "#302A4F",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: "#FFF",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    fontFamily: "JetBrainsMono-Medium",
    textAlignVertical: "top",
    minHeight: 100,
  },
  generateButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 24,
  },
  generateButtonDisabled: {
    backgroundColor: "#555",
  },
  generateButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontFamily: "JetBrainsMono-Bold",
    marginLeft: 8,
  },
  resultContainer: {
    marginTop: 16,
  },
  websitePreview: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#302A4F",
  },
  websitePrompt: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
    marginBottom: 8,
  },
  websiteTimestamp: {
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    color: "#777",
    marginBottom: 16,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 16,
  },
  previewButton: {
    backgroundColor: "#007AFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  saveButton: {
    backgroundColor: "#34C759",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  clearButton: {
    backgroundColor: "#FF3B30",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  actionButtonText: {
    color: "#FFF",
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    marginLeft: 6,
  },
  codePreview: {
    backgroundColor: "#1E1E1E",
    borderRadius: 8,
    padding: 12,
    maxHeight: 150,
    borderWidth: 1,
    borderColor: "#444",
  },
  codeText: {
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    color: "#88C999",
    lineHeight: 16,
  },

  // Podcast Generation Screen Styles
  podcastStyleContainer: {
    marginBottom: 24,
  },
  podcastStyleChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#302A4F",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    marginRight: 10,
    minWidth: 80,
    alignItems: "center",
  },
  podcastStyleChipSelected: {
    backgroundColor: "#FF6B6B",
    borderColor: "#FF6B6B",
  },
  podcastStyleChipText: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
  },
  podcastStyleChipTextSelected: {
    color: "#FFF",
  },
  voiceSettingsContainer: {
    marginBottom: 24,
  },
  voiceSettingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  voiceSettingLabel: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Medium",
    color: "#FFF",
    flex: 1,
  },
  voiceSettingValue: {
    fontSize: 14,
    fontFamily: "JetBrainsMono-Bold",
    color: "#007AFF",
    minWidth: 60,
    textAlign: "right",
  },
  sliderContainer: {
    flex: 2,
    marginLeft: 12,
  },
  genderSelector: {
    flexDirection: "row",
    flex: 2,
    justifyContent: "flex-end",
  },
  genderOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#302A4F",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    marginLeft: 6,
  },
  genderOptionSelected: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  genderOptionText: {
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
  },
  genderOptionTextSelected: {
    color: "#FFF",
  },
  podcastPreview: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#302A4F",
  },
  podcastTitle: {
    fontSize: 16,
    fontFamily: "JetBrainsMono-Bold",
    color: "#FFF",
    marginBottom: 8,
  },
  podcastMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  podcastMetaText: {
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
  },
  scriptPreview: {
    backgroundColor: "#1E1E1E",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: "#444",
  },
  scriptText: {
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    color: "#E0E0E0",
    lineHeight: 16,
  },
  audioPlayer: {
    backgroundColor: "#2A2A2A",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  audioControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  playButton: {
    backgroundColor: "#007AFF",
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 12,
  },
  audioTime: {
    fontSize: 12,
    fontFamily: "JetBrainsMono-Medium",
    color: "#AAA",
    minWidth: 50,
    textAlign: "center",
  },
  progressContainer: {
    flex: 1,
    marginHorizontal: 12,
  },
  progressBar: {
    height: 4,
    backgroundColor: "#444",
    borderRadius: 2,
  },
  progressFill: {
    height: 4,
    backgroundColor: "#007AFF",
    borderRadius: 2,
  },
  downloadButton: {
    backgroundColor: "#34C759",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    alignSelf: "center",
  },
  podcastActionButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 16,
  },
  generatePodcastButton: {
    backgroundColor: "#FF6B6B",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 24,
  },
  generatePodcastButtonDisabled: {
    backgroundColor: "#555",
  },
  generatePodcastButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontFamily: "JetBrainsMono-Bold",
    marginLeft: 8,
  },
});
