import mongoose, { Schema, Document } from 'mongoose';

export type TransactionType = 'course_purchase' | 'subscription';
export type TransactionStatus = 'pending' | 'success' | 'failed';

export interface ITransaction extends Document {
  user: mongoose.Types.ObjectId;
  /** Unique reference generated by us and sent to Paystack; doubles as the webhook idempotency key. */
  reference: string;
  type: TransactionType;
  course?: mongoose.Types.ObjectId;
  amount: number;
  currency: string;
  status: TransactionStatus;
  paystackPayload?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

const TransactionSchema: Schema = new Schema<ITransaction>(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    reference: {
      type: String,
      required: true,
      unique: true,
    },
    type: {
      type: String,
      enum: ['course_purchase', 'subscription'],
      required: true,
    },
    course: {
      type: Schema.Types.ObjectId,
      ref: 'Course',
    },
    amount: {
      type: Number,
      required: true,
    },
    currency: {
      type: String,
      default: 'NGN',
    },
    status: {
      type: String,
      enum: ['pending', 'success', 'failed'],
      default: 'pending',
      index: true,
    },
    paystackPayload: {
      type: Schema.Types.Mixed,
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model<ITransaction>('Transaction', TransactionSchema);
